### ISSUE TITLE
Issue 2 User can turn their car.

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create data model for direction
- [x] add event listner for arrows key
- [x] compare key event and update image class
- [x] add css for rotating image
- [x] add css for animation when car rotate
