### ISSUE TITLE
issue 3 User can start their car.

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add coordinates X and Y to the data model
- [x] use absolute positioning for your image
- [x] add add event listener for space
- [x] add interval
